The "addinstance" script now requests the email address to be used as sender for all system generated messages.

diff --git a/scripts/addinstance b/scripts/addinstance
--- a/scripts/addinstance
+++ b/scripts/addinstance
@@ -62,7 +62,8 @@ if [ -d '/etc/nginx/sites-available' ]; then
 elif [ -d '/etc/nginx/conf.d' ]; then
   NGINX_CONF='/etc/nginx/conf.d'
 else
-  stopInstallation
+  echo "ERROR: Could not identify NGINX virtual host configuration folder."
+	exit
 fi
 
 #######################################
@@ -273,6 +274,16 @@ fi
 
 SMTP_PARAMS=($(awk -F: '{$1=$1} 1' <<<"${result}"))
 
+EMAIL_SENDER=$(dialog --backtitle 'Vilfredo new instance installation' --title "System messages email sender" --inputbox "Please enter the email address which will be used as sender for all system generated messages.\nTo prevent messages from being marked as spam, the mail server should have been configured to digitally sign all email messages from that domain using DKIM, the DKIM public key should be uploaded to the DNS for the domain and a SPF record should be added to.\n\nIf you do not know how to proceed, it is strongly suggested to specify an email address on a domain which the selected SMTP server is already able to deliver messages from without errors." 16 80 admin$DOMAIN --output-fd 1)
+if [ "$?" != "0" ]; then
+  quitInstallation
+fi
+
+GOOGLE_CODE=$(dialog --backtitle 'Vilfredo new instance installation' --inputbox "Please enter the Google unique identification code to track this website using Google Analytics.\nThis can be safely omitted and entered later by editing the following file:\n\n/home/$NAME/vilfredo-client/static/templates/analytics.template.html" 13 80 UA-XXXXXXXX-X --output-fd 1)
+if [ "$?" != "0" ]; then
+  quitInstallation
+fi
+
 ###########################
 # Create the MySQL database
 ###########################
@@ -355,6 +366,7 @@ sudo -u $NAME -s -- <<EOF
   sed -i "s!var/log/vilfredo/vilfredo-vr.log!var/log/$NAME/vr.log!g" /etc/$NAME/settings.cfg
   sed -i "s/MAIL_SERVER = 'localhost/MAIL_SERVER = '${SMTP_PARAMS[0]}/g" /etc/$NAME/settings.cfg
   sed -i "s/MAIL_PORT = 25/MAIL_PORT = ${SMTP_PARAMS[1]}/g" /etc/$NAME/settings.cfg
+  sed -i "s/'admin@' + SITE_DOMAIN/'$EMAIL_SENDER'/g" /etc/$NAME/settings.cfg
 EOF
 if [ "$SMTP_PARAMS[2]" != '' ]; then
   sudo -u $NAME sed -i "s/MAIL_USERNAME = None/MAIL_USERNAME = '${SMTP_PARAMS[2]}'/g" /etc/$NAME/settings.cfg
